using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DG.Tweening;
public class LandAnimationControl : MonoBehaviour
{
    public GameObject paiziObj;
    private Sequence seq;

    public AnimationClip PaiziPlayAnim;
    public AnimationClip PaiziStopAnim;

    private void Start()
    {
        //var seq = DOTween.Sequence();
        //seq.Append(paiziObj.transform.DOScale(new Vector3(1.2f, 1.2f, 1f), 0.5f).SetEase(Ease.Linear));
        //seq.Append(paiziObj.transform.DOScale(new Vector3(1f, 1f, 1f), 0.5f).SetEase(Ease.Linear));
        //seq.SetLoops(-1);
    }
    public void showPuzzle()
    {
        //puzzleObj.SetActive(true);
    }

    public void playUnLockTipAnim()
    {
        if (PaiziPlayAnim != null)
        {
            paiziObj.GetComponent<Animator>().Play(PaiziPlayAnim.name);
        }
    }
    public void stopUnLockTipAnim()
    {
        if (PaiziPlayAnim != null)
        {
            paiziObj.GetComponent<Animator>().Play(PaiziStopAnim.name);
        }
        //paiziObj.transform.DOKill();
    }
}
