using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;


public class RedPackNum : MonoBehaviour
{
    public Text textNumTv;

    private void OnEnable()
    {
        //textNumTv.text = GameObject.Find("TitleView").GetComponent<TitleControl>().getBottomRedPackNum + "次";
        textNumTv.text =CoinNumControl.GetIns().getRemainRewardNum + "次";

    }
    private void Update()
    {
        //textNumTv.text = GameObject.Find("TitleView").GetComponent<TitleControl>().getBottomRedPackNum + "次";
        textNumTv.text = CoinNumControl.GetIns().getRemainRewardNum + "次";
    }
}
