using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class land_item_type : MonoBehaviour
{
    public Image landType;

    public void setLandType(int type)
    {
        switch (type)
        {
            case 1:
                landType.overrideSprite = Resources.Load(ResourcesUtil.getRes().getLandRes(0), typeof(Sprite)) as Sprite;
                break;
            case 2:
                landType.overrideSprite = Resources.Load(ResourcesUtil.getRes().getLandRes(1), typeof(Sprite)) as Sprite;
                break;
            case 3:
                landType.overrideSprite = Resources.Load(ResourcesUtil.getRes().getLandRes(2), typeof(Sprite)) as Sprite;
                break;
            default:
                landType.overrideSprite = Resources.Load(ResourcesUtil.getRes().getLandRes(0), typeof(Sprite)) as Sprite;
                break;
        }
    }
}
